---
- hosts: cisco

  tasks:
    - name: Facts
      cisco.ios.ios_facts:
        gather_subset: min
        gather_network_resources: interfaces
      register: facts_output
    
    - name: print output
      debug:
        var: facts_output
